# csv to json

In [3]:
import pandas as pd

In [4]:
goog = pd.read_csv('goog.csv')

In [5]:
goog.head()

,Date,High,Low,Open,Close,Volume,Adj Close
0,2019-01-01,1117.329956,1014.070007,1016.570007,1116.369995,30714000,1116.369995
1,2019-02-01,1147.000000,1086.000000,1112.400024,1119.920044,28932700,1119.920044
2,2019-03-01,1231.790039,1123.300049,1124.900024,1173.310059,31660000,1173.310059
3,2019-04-01,1289.270020,1175.000000,1184.099976,1188.479980,27858700,1188.479980
4,2019-05-01,1190.849976,1100.180054,1188.050049,1103.630005,33317400,1103.630005

In [10]:
# orient columns (default), index, records, split
goog.to_json(orient='split')

'{"columns":["Date","High","Low","Open","Close","Volume","Adj Close"],"index":[0,1,2,3,4,5,6,7,8,9,10,11,12],"data":[["2019-01-01",1117.3299560547,1014.0700073242,1016.5700073242,1116.3699951172,30714000,1116.3699951172],["2019-02-01",1147.0,1086.0,1112.4000244141,1119.9200439453,28932700,1119.9200439453],["2019-03-01",1231.7900390625,1123.3000488281,1124.9000244141,1173.3100585938,31660000,1173.3100585938],["2019-04-01",1289.2700195312,1175.0,1184.0999755859,1188.4799804688,27858700,1188.4799804688],["2019-05-01",1190.8499755859,1100.1800537109,1188.0500488281,1103.6300048828,33317400,1103.6300048828],["2019-06-01",1124.1099853516,1025.0,1065.5,1080.9100341797,34096800,1080.9100341797],["2019-07-01",1265.5500488281,1093.7030029297,1098.0,1216.6800537109,32947500,1216.6800537109],["2019-08-01",1234.1099853516,1140.1400146484,1214.0300292969,1188.0999755859,28882400,1188.0999755859],["2019-09-01",1248.3000488281,1163.1999511719,1177.0300292969,1219.0,26899400,1219.0],["2019-10-01",1299.3100585938,1162.4300537109,1219.0,1260.1099853516,28758300,1260.1099853516],["2019-11-01",1335.5290527344,1260.5,1265.0,1304.9599609375,24923400,1304.9599609375],["2019-12-01",1365.0,1279.0,1301.0,1337.0200195312,27357100,1337.0200195312],["2020-01-01",1503.2139892578,1341.5500488281,1341.5500488281,1485.9499511719,22386700,1485.9499511719]]}'

In [11]:
import json

In [12]:
json.loads(goog.to_json(orient='records'))

[{'Date': '2019-01-01',
  'High': 1117.3299560547,
  'Low': 1014.0700073242,
  'Open': 1016.5700073242,
  'Close': 1116.3699951172,
  'Volume': 30714000,
  'Adj Close': 1116.3699951172},
 {'Date': '2019-02-01',
  'High': 1147.0,
  'Low': 1086.0,
  'Open': 1112.4000244141,
  'Close': 1119.9200439453,
  'Volume': 28932700,
  'Adj Close': 1119.9200439453},
 {'Date': '2019-03-01',
  'High': 1231.7900390625,
  'Low': 1123.3000488281,
  'Open': 1124.9000244141,
  'Close': 1173.3100585938,
  'Volume': 31660000,
  'Adj Close': 1173.3100585938},
 {'Date': '2019-04-01',
  'High': 1289.2700195312,
  'Low': 1175.0,
  'Open': 1184.0999755859,
  'Close': 1188.4799804688,
  'Volume': 27858700,
  'Adj Close': 1188.4799804688},
 {'Date': '2019-05-01',
  'High': 1190.8499755859,
  'Low': 1100.1800537109,
  'Open': 1188.0500488281,
  'Close': 1103.6300048828,
  'Volume': 33317400,
  'Adj Close': 1103.6300048828},
 {'Date': '2019-06-01',
  'High': 1124.1099853516,
  'Low': 1025.0,
  'Open': 1065.5,
  'Close': 1080.9100341797,
  'Volume': 34096800,
  'Adj Close': 1080.9100341797},
 {'Date': '2019-07-01',
  'High': 1265.5500488281,
  'Low': 1093.7030029297,
  'Open': 1098.0,
  'Close': 1216.6800537109,
  'Volume': 32947500,
  'Adj Close': 1216.6800537109},
 {'Date': '2019-08-01',
  'High': 1234.1099853516,
  'Low': 1140.1400146484,
  'Open': 1214.0300292969,
  'Close': 1188.0999755859,
  'Volume': 28882400,
  'Adj Close': 1188.0999755859},
 {'Date': '2019-09-01',
  'High': 1248.3000488281,
  'Low': 1163.1999511719,
  'Open': 1177.0300292969,
  'Close': 1219.0,
  'Volume': 26899400,
  'Adj Close': 1219.0},
 {'Date': '2019-10-01',
  'High': 1299.3100585938,
  'Low': 1162.4300537109,
  'Open': 1219.0,
  'Close': 1260.1099853516,
  'Volume': 28758300,
  'Adj Close': 1260.1099853516},
 {'Date': '2019-11-01',
  'High': 1335.5290527344,
  'Low': 1260.5,
  'Open': 1265.0,
  'Close': 1304.9599609375,
  'Volume': 24923400,
  'Adj Close': 1304.9599609375},
 {'Date': '2019-12-01',
  'High': 1365.0,
  'Low': 1279.0,
  'Open': 1301.0,
  'Close': 1337.0200195312,
  'Volume': 27357100,
  'Adj Close': 1337.0200195312},
 {'Date': '2020-01-01',
  'High': 1503.2139892578,
  'Low': 1341.5500488281,
  'Open': 1341.5500488281,
  'Close': 1485.9499511719,
  'Volume': 22386700,
  'Adj Close': 1485.9499511719}]